server:
  port: 8000

spring:
  application:
    name: jczong-gateway
  cloud:
    nacos:
      discovery:
        serverAddr: 192.168.222.1:8848
        username: 'nacos'
        password: 'nacos'
      config:
        serverAddr: 192.168.222.1:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      - nacos:jczong-gateway.yaml?refreshEnabled=true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 添加日志配置，便于调试
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.client.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG